apiVersion: v1
kind: ServiceAccount
metadata:
  name: localhostrun-controller
  namespace: lhr-ingress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: localhostrun-controller-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: localhostrun-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: localhostrun-controller-role
subjects:
- kind: ServiceAccount
  name: localhostrun-controller
  namespace: lhr-ingress
